### ISSUE TITLE
Figure out how to do collisions properly

### ISSUE THREAD

**Issue by BoxyUwU** [Supbscripter/GMTK-Jam#7]
We need to make it so that Enemies Bullets and Players don't push each other around when they collide (without making it so that enemies and players can walk out of the map). 
I would also like it if Enemies would totally bypass the platforms and have no physics interaction with them. This should be possible but doesnt seem to be working.
https://docs.unity3d.com/Manual/LayerBasedCollision.html This is what I tried to implement
Another requirement is that we need OnTriggerEnter2D() and OnCollisionEnter2D() to continue working as that is how we are damaging enemies with bullets and registering when the player has landed after a jump.

If you try and do this one I would probably reccomend asking for help in the GMTK Discord server.

**Comment by BlueFire561** [comment]
> We need to make it so that Enemies Bullets and Players don't push each other around when they collide (without making it so that enemies and players can walk out of the map).
So:
- Enemies and bullets wont push because they are deleted on collision
- Bullets and players should be fine because they shouldn't really interact 
As for the enemies:
- It depends whether the enemies will die when colliding with the player or will they stay alive and the player gets invincibility frames or something
- If they die its easy because no pushing neccessary
- If were going with them staying alive then I guess we would just let the player and enemy layer collide in the collision matrix and then let the enemy push the the player because they shouldnt get out of the world as we can just bind them to it or put in world borders
